name: handmade_cake
description: Craete Handmade Cake .Make Moment
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.18.6
  riverpod: ^2.3.2
  flutter_svg: ^2.0.5
  hooks_riverpod: ^2.3.2
  json_annotation: ^4.8.1
  flutter_launcher_icons: ^0.13.1
  get_it: ^7.6.0
  http: ^0.13.6
  shared_preferences: ^2.1.1
  package_info_plus: ^4.0.2
  url_launcher: ^6.1.11
  app_tracking_transparency: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.17
  json_serializable: ^6.6.2
  build_runner: ^2.3.3

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/imgs/
    - assets/fonts/

  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR-Thin.otf
          weight: 100
        - asset: assets/fonts/NotoSansKR-Light.otf
          weight: 300
        - asset: assets/fonts/NotoSansKR-Regular.otf
          weight: 400
        - asset: assets/fonts/NotoSansKR-Medium.otf
          weight: 500
        - asset: assets/fonts/NotoSansKR-Bold.otf
          weight: 700
        - asset: assets/fonts/NotoSansKR-Black.otf
          weight: 900


flutter_native_splash:
  full: true
  image: assets/imgs/image_splash.png
  image_dark: assets/imgs/image_splash.png
  color: "#01205F"
  color_dark: "#01205F"

  # Android 12 이상 버전에서 적용
  android_12:
    full: true
    image: assets/imgs/image_splash.png
    image_dark: assets/imgs/image_splash.png
    color: "#01205F"
    color_dark: "#01205F"